### ISSUE TITLE
What is the license for the images

### ISSUE THREAD

**Issue by edg2s** [chromezh/unicode_nushu#1]
Form the readme:
> Code for building the data is distributed under MIT license.
> Nushu glyphs and web fonts follow the original license.

What is the "original license" referred to here?

Thanks,

**Comment by sgalal** [comment]
The images are taken from the book 女书规范字书法字帖. I personally believe that you can use the images as long as you attribute the original authors. If you want to be sure enough, you can contact the authors for confirmation.

Besides, you can use the open-source Nushu fonts, like [Noto Traditional Nushu](https://github.com/notofonts/NotoTraditionalNushu) or [Noto Sans Nüshu](https://github.com/notofonts/noto-sans-nushu). These fonts have clearer licenses.

**Comment by edg2s** [comment]
Thanks.

**Comment by sgalal** [comment]
Hi, @edg2s, the images are now moved to another repository: [nushu-script/nushu-nsgfzsfzt](https://github.com/nushu-script/nushu-nsgfzsfzt).
